services:
  monerod:
    image: monerod:0.18.3.4
    pull_policy: build
    build:
      context: .
      args:
        - MONERO_VERSION=0.18.3.4
        # - PUID=1000
        # - PGID=1000
    restart: unless-stopped
    container_name: monerod
    volumes:
      - ./data:/app/monero/bitmonero # monero data
      - ./monerod.conf:/etc/monero/monerod.conf         # monero config
    ports:
      - 18081:18081     # rpc
      # - 18089:18089   # restricted rpc
      # - 18080:18080   # p2p
    environment:
      - PUID=1000
      - PGID=1000