services:
  monerod:
    image: oregonpillow/monerod:latest
    container_name: monerod
    restart: unless-stopped
    volumes:
      # IMPORTANT: data folder must exist before starting container
      - ./data:/app/monero/bitmonero
      - ./monerod.conf:/app/monero/monerod.conf
    ports:
      - 18081:18081 # rpc
      - 18089:18089 # restricted rpc
      - 18080:18080 # p2p
