services:
  monerod:
    image: monerod:v0.18.3.4
    pull_policy: build
    build:
      context: .
    user: "1000:1000"
    restart: unless-stopped
    container_name: monerod
    volumes:
      - /home/debian/.bitmonero:/home/monero/.bitmonero # monero data
      - ./monerod.conf:/etc/monero/monerod.conf         # monero config
    ports:
      - 18081:18081     # rpc
      # - 18089:18089   # restricted rpc
      # - 18080:18080   # p2p
