services:
  monerod:
    image: monerod:0.18.3.4
    restart: unless-stopped
    container_name: monerod
    pull_policy: build
    build:
      context: .
      args:
        - MONERO_VERSION=0.18.3.4
    volumes:
      - ./data:/app/monero/bitmonero
      - ./monerod.conf:/app/monero/monerod.conf
    ports:
      - 18081:18081     # rpc
      - 18089:18089   # restricted rpc
      - 18080:18080   # p2p
    environment:
      - PUID=1000
      - PGID=1000