#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /app/monero/bin s6-setuidgid abc /app/monero/bin/monerod --non-interactive --config-file=/app/monero/monerod.conf
