#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /run/monerod-temp
mkdir -p /app/monero/bitmonero
mkdir -p /app/monero/bin

# permissions
lsiown -R abc:abc \
    /app/monero/bitmonero \
    /run/monerod-temp \
    /app/monero/bin
