name: Build and Push Docker image

on:
  push:
    branches:
      - "master"

env:
  MONERO_VERSION: 0.18.3.4
  PUID: 1000
  PGID: 1000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/monerod:latest
            ${{ vars.DOCKER_USERNAME }}/monerod:${{ env.MONERO_VERSION }}
          build-args: |
            PLATFORM=linux-x64
            MONERO_VERSION=${{ env.MONERO_VERSION }}
            PUID=${{ env.PUID }}
            PGID=${{ env.PGID }}
